# Generated by Django 4.1.5 on 2023-01-06 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_subscription_profile_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='favorite',
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorite',
            field=models.ManyToManyField(choices=[('AC', 'Action'), ('AD', 'Adventure'), ('BI', 'Biography'), ('CO', 'Comedy'), ('CR', 'Crime'), ('HI', 'History'), ('HO', 'Horror'), ('DR', 'Drama'), ('SC', 'Sci-Fi')], default=None, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
