# Generated by Django 4.1.5 on 2023-01-06 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_favorite_user_remove_favorite_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='favorite',
            field=models.ManyToManyField(default=None, limit_choices_to=[('AC', 'Action'), ('AD', 'Adventure'), ('BI', 'Biography'), ('CO', 'Comedy'), ('CR', 'Crime'), ('HI', 'History'), ('HO', 'Horror'), ('DR', 'Drama'), ('SC', 'Sci-Fi')], related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
