# Generated by Django 4.1.5 on 2023-01-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_favorite_user_remove_favorite_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='favorite',
            field=models.CharField(choices=[('AC', 'Action'), ('AD', 'Adventure'), ('BI', 'Biography'), ('CO', 'Comedy'), ('CR', 'Crime'), ('HI', 'History'), ('HO', 'Horror'), ('DR', 'Drama'), ('SC', 'Sci-Fi')], default=None, max_length=2, unique=True),
        ),
    ]
