# Generated by Django 4.1.5 on 2023-01-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_favorite_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='assets/img/default.png', upload_to='media/users'),
        ),
    ]
