# Generated by Django 4.1.5 on 2023-01-09 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ManyToManyField(related_name='user_favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
