# Generated by Django 4.1.5 on 2023-01-11 00:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='favorite',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AC', 'Action'), ('AD', 'Adventure'), ('BI', 'Biography'), ('CO', 'Comedy'), ('CR', 'Crime'), ('HI', 'History'), ('HO', 'Horror'), ('DR', 'Drama'), ('SC', 'Sci-Fi')], default=None, max_length=2, unique=True),
        ),
    ]
