# Generated by Django 4.1.5 on 2023-01-11 01:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_favorite_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.AddField(
            model_name='favorite',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='user_favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
