# Generated by Django 4.1.5 on 2023-01-11 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_favorite_users_favorite_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='users',
        ),
    ]
