# Generated by Django 4.1.5 on 2023-01-12 00:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_profile_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ACTION', 'Action'), ('ADVENTURE', 'Adventure'), ('BIOGRAPHY', 'Biography'), ('COMEDY', 'Comedy'), ('CRIME', 'Crime'), ('HISTORY', 'History'), ('HORROR', 'Horror'), ('DRAMA', 'Drama'), ('SCIFI', 'Sci-Fi')], default=None, max_length=10),
        ),
    ]
