# Generated by Django 4.1.5 on 2023-01-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_profile_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('TR', 'Trial'), ('ST', 'Standard'), ('PR', 'Premium'), ('ID', 'Idle')], default='TR', max_length=2),
        ),
    ]
