# Generated by Django 4.1.5 on 2023-01-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_rename_tvseries_series'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['-created_at'], name='stream_seri_created_5b48ba_idx'),
        ),
    ]
