# Generated by Django 4.1.5 on 2023-01-22 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_series_stream_seri_created_5b48ba_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'movie', 'verbose_name_plural': 'movies'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'series', 'verbose_name_plural': 'series'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='stream/movies/posters', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.FileField(upload_to='stream/movies/trailers', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mkv', 'flv', 'wmv'])]),
        ),
        migrations.AlterField(
            model_name='series',
            name='season_poster',
            field=models.ImageField(upload_to='stream/series/posters', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='series',
            name='season_trailer',
            field=models.ImageField(upload_to='stream/series/trailers', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mkv', 'flv', 'wmv'])]),
        ),
    ]
