# Generated by Django 4.1.5 on 2023-01-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_alter_movie_options_alter_series_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='episode_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='series',
            name='episode_title',
            field=models.CharField(default='episode title', max_length=100),
        ),
    ]
