# Generated by Django 4.1.5 on 2023-01-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_series_episode_number_series_episode_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='episode_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='series',
            name='episode_title',
            field=models.CharField(max_length=100),
        ),
    ]
