# Generated by Django 4.1.5 on 2023-01-22 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0007_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
