# Generated by Django 4.1.5 on 2023-01-22 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0008_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='season_trailer',
            field=models.FileField(upload_to='stream/series/trailers', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mkv', 'flv', 'wmv'])]),
        ),
    ]
