# Generated by Django 4.1.5 on 2023-01-23 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0011_episode_series_alter_episode_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_episodes', to='stream.series'),
        ),
    ]
