# Generated by Django 4.1.5 on 2023-01-31 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reaction', '0002_reaction_users_reactions_remove_reaction_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='likes',
            new_name='like',
        ),
    ]
